Mask: Hello Frog!! Welcome to the maze, where you find anything any one...
Frog: I am looking my friend called "Purple"...
Mask: I don't know but you can find him inside this maze and can you help to collect fruits which will you find in the way...

*Okay, I will help you
*No, I only want to find him

- Mask: Okay, you can go on the same path and you will find your friend but carefully, you can find some traps putted by the villagers...

Frog: Okay!!

 